<?php

use Illuminate\Database\Seeder;

class ArticulosTableSeeder extends Seeder {

    public function run() {
        $arts = array(
            array('id' => '1', 'nombre' => 'Planta Eléctrica 6.50 kva monofásica', 'tipo_articulo_id' => '1', 'ind_excento' => '0'),
            array('id' => '2', 'nombre' => 'Planta Eléctrica 50 kva insonora', 'tipo_articulo_id' => '1', 'ind_excento' => '0'),
            array('id' => '3', 'nombre' => 'Planta Eléctrica 80 kva insonora', 'tipo_articulo_id' => '1', 'ind_excento' => '0'),
            array('id' => '4', 'nombre' => 'Planta Eléctrica 85 kva insonora', 'tipo_articulo_id' => '1', 'ind_excento' => '0'),
            array('id' => '5', 'nombre' => 'Planta Eléctrica 90 kva insonora', 'tipo_articulo_id' => '1', 'ind_excento' => '0'),
            array('id' => '6', 'nombre' => 'Planta Eléctrica 100 kva insonora', 'tipo_articulo_id' => '1', 'ind_excento' => '0'),
            array('id' => '7', 'nombre' => 'Planta Eléctrica 105 kva insonora', 'tipo_articulo_id' => '1', 'ind_excento' => '0'),
            array('id' => '8', 'nombre' => 'Planta Eléctrica 110 kva insonora', 'tipo_articulo_id' => '1', 'ind_excento' => '0'),
            array('id' => '9', 'nombre' => 'Planta Eléctrica modelo mp 110', 'tipo_articulo_id' => '1', 'ind_excento' => '0'),
            array('id' => '10', 'nombre' => 'Planta Eléctrica 120 kva insonora', 'tipo_articulo_id' => '1', 'ind_excento' => '0'),
            array('id' => '11', 'nombre' => 'Planta Eléctrica 125 kva insonora (2)', 'tipo_articulo_id' => '1', 'ind_excento' => '0'),
            array('id' => '12', 'nombre' => 'Planta Eléctrica 135 kva insonora', 'tipo_articulo_id' => '1', 'ind_excento' => '0'),
            array('id' => '13', 'nombre' => 'Planta Eléctrica 140 kva insonora', 'tipo_articulo_id' => '1', 'ind_excento' => '0'),
            array('id' => '14', 'nombre' => 'Planta Eléctrica 150 kva insonora (2)', 'tipo_articulo_id' => '1', 'ind_excento' => '0'),
            array('id' => '15', 'nombre' => 'Planta Eléctrica 155 kva insonora', 'tipo_articulo_id' => '1', 'ind_excento' => '0'),
            array('id' => '16', 'nombre' => 'Planta Eléctrica 165 kva insonora', 'tipo_articulo_id' => '1', 'ind_excento' => '0'),
            array('id' => '17', 'nombre' => 'Planta Eléctrica 180 kva insonora', 'tipo_articulo_id' => '1', 'ind_excento' => '0'),
            array('id' => '18', 'nombre' => 'Planta Eléctrica 185 kva insonora', 'tipo_articulo_id' => '1', 'ind_excento' => '0'),
            array('id' => '19', 'nombre' => 'Planta Eléctrica 190 kva insonora', 'tipo_articulo_id' => '1', 'ind_excento' => '0'),
            array('id' => '20', 'nombre' => 'Planta Eléctrica 200 kva insonora', 'tipo_articulo_id' => '1', 'ind_excento' => '0'),
            array('id' => '21', 'nombre' => 'Planta Eléctrica 220 kva insonora', 'tipo_articulo_id' => '1', 'ind_excento' => '0'),
            array('id' => '22', 'nombre' => 'Planta Eléctrica 230 kva insonora', 'tipo_articulo_id' => '1', 'ind_excento' => '0'),
            array('id' => '23', 'nombre' => 'Planta Eléctrica 250 kva insonora', 'tipo_articulo_id' => '1', 'ind_excento' => '0'),
            array('id' => '24', 'nombre' => 'Planta Eléctrica 270 kva insonora', 'tipo_articulo_id' => '1', 'ind_excento' => '0'),
            array('id' => '25', 'nombre' => 'Planta Eléctrica 280 kva insonora', 'tipo_articulo_id' => '1', 'ind_excento' => '0'),
            array('id' => '26', 'nombre' => 'Planta Eléctrica 300 kva insonora', 'tipo_articulo_id' => '1', 'ind_excento' => '0'),
            array('id' => '27', 'nombre' => 'Planta Eléctrica 330 kva insonora', 'tipo_articulo_id' => '1', 'ind_excento' => '0'),
            array('id' => '28', 'nombre' => 'Planta Eléctrica 350 kva insonora', 'tipo_articulo_id' => '1', 'ind_excento' => '0'),
            array('id' => '29', 'nombre' => 'Planta Eléctrica 375 kva insonora', 'tipo_articulo_id' => '1', 'ind_excento' => '0'),
            array('id' => '30', 'nombre' => 'Planta Eléctrica 380 kva insonora', 'tipo_articulo_id' => '1', 'ind_excento' => '0'),
            array('id' => '31', 'nombre' => 'Planta Eléctrica 387 kva insonora', 'tipo_articulo_id' => '1', 'ind_excento' => '0'),
            array('id' => '32', 'nombre' => 'Planta Eléctrica 400 kva insonora', 'tipo_articulo_id' => '1', 'ind_excento' => '0'),
            array('id' => '33', 'nombre' => 'Planta Eléctrica 450 kva insonora', 'tipo_articulo_id' => '1', 'ind_excento' => '0'),
            array('id' => '34', 'nombre' => 'Planta Eléctrica 500 kva insonora', 'tipo_articulo_id' => '1', 'ind_excento' => '0'),
            array('id' => '35', 'nombre' => 'Planta Eléctrica 750 kva insonora', 'tipo_articulo_id' => '1', 'ind_excento' => '0'),
            array('id' => '36', 'nombre' => 'Planta Eléctrica 800 kva insonora', 'tipo_articulo_id' => '1', 'ind_excento' => '0'),
            array('id' => '37', 'nombre' => 'Planta Eléctrica varias', 'tipo_articulo_id' => '1', 'ind_excento' => '0'),
            array('id' => '38', 'nombre' => 'Consola avolites pearl 2004', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '39', 'nombre' => 'Consola leprecom mx 2400', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '40', 'nombre' => 'Consola leprecom 3000', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '41', 'nombre' => 'Consola leprecom 612', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '42', 'nombre' => 'Consola leprecom 624', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '43', 'nombre' => 'Consola lep 1624', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '44', 'nombre' => 'Consola wholehog it', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '45', 'nombre' => 'Martin mac 600 wash', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '46', 'nombre' => 'Martin mac 700', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '47', 'nombre' => 'Maquina de humo f100', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '48', 'nombre' => 'Maquina de humo df50', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '49', 'nombre' => 'Maquina de humo martin magnum 2000', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '50', 'nombre' => 'Mac 550', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '51', 'nombre' => 'Mac 700 profile', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '52', 'nombre' => 'Maleta de luces', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '53', 'nombre' => 'Microfono sennheiser 835', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '54', 'nombre' => 'Mini brutos', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '55', 'nombre' => 'Dimmer leprecom 2400 VX', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '56', 'nombre' => 'Par 64', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '57', 'nombre' => 'Par 64 ACL', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '58', 'nombre' => 'Par soof', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '59', 'nombre' => 'Proyector de video', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '60', 'nombre' => 'Parnel etc source four 575', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '61', 'nombre' => 'Seguidor 1200 MCR tiro medio', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '62', 'nombre' => 'Seguidor lycian 1275 tiro largo', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '63', 'nombre' => 'Seguidor super trooper xenon 1600', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '64', 'nombre' => 'Seguidor super trooper xenon 2500', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '65', 'nombre' => 'Silla seguidor', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '66', 'nombre' => 'Sistema de intercom', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '67', 'nombre' => 'Slevee block 26x30', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '68', 'nombre' => 'Source four parnet 575', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '69', 'nombre' => 'Fresnel baby 8 750 watt', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '70', 'nombre' => 'Fresnel color tram 1000 watt', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '71', 'nombre' => 'Fresnel 2000 watt', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '72', 'nombre' => 'Fresnel 8 alman 1000 watt', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '73', 'nombre' => 'Fresnel 650 wats', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '74', 'nombre' => 'Fuentes clear com', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '75', 'nombre' => 'Fresnel 500 wats', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '76', 'nombre' => 'Likos etc source four 575', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '77', 'nombre' => 'Likos etc source four 26', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '78', 'nombre' => 'Likos etc source four 36', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '79', 'nombre' => 'Likos etc 10', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '80', 'nombre' => 'Likos etc zoom 15" 30', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '81', 'nombre' => 'Liko etc zoom 25" 50', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '82', 'nombre' => 'Liko etc source four 575', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '83', 'nombre' => 'Liko baby alman 500 watt', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '84', 'nombre' => 'Liko alman 750 watt', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '85', 'nombre' => 'Vl 2500 spot', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '86', 'nombre' => 'Vl 2500 wash', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '87', 'nombre' => 'Varilight vl 3000', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '88', 'nombre' => 'Controlador luces light jockey', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '89', 'nombre' => 'Color blast', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '90', 'nombre' => 'Breaker 400 amp', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '91', 'nombre' => 'Gennis works', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '92', 'nombre' => 'Intercom clear com', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '93', 'nombre' => 'Lamparas metal high ligth', 'tipo_articulo_id' => '2', 'ind_excento' => '0'),
            array('id' => '94', 'nombre' => 'Circulo 3 mts de diametro 12x12', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '95', 'nombre' => 'Circulo 5 mts de diametro 12x12', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '96', 'nombre' => 'Circulo liviano 4 mts 12x12', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '97', 'nombre' => 'Circulo pesado 6 mts 12x12', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '98', 'nombre' => 'Truss mk2 1mts', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '99', 'nombre' => 'Truss mk2 2,50 mts', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '100', 'nombre' => 'Truss mk2 1,5 mts, tomcat', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '101', 'nombre' => 'Truss mk2 1mts tomcat', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '102', 'nombre' => 'Truss mk2, 2 mts tomcat', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '103', 'nombre' => 'Truss mk2 12x12 1 mts', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '104', 'nombre' => 'Truss mk2 12x12 1,50mts', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '105', 'nombre' => 'Truss mk2 12x12 2mts', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '106', 'nombre' => 'Truss mk2 12x12 3mts', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '107', 'nombre' => 'Truss mk2 12x12 tomcat', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '108', 'nombre' => 'Truss mk2 3 mts tomcat', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '109', 'nombre' => 'Truss prt 20,5 3mts tomcat', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '110', 'nombre' => 'Truss prt 26x30 tomcat', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '111', 'nombre' => 'Tarima modular 18x16 mts', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '112', 'nombre' => 'Tarima de 14*4,80 mts', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '113', 'nombre' => 'Techo 8*8 global truss', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '114', 'nombre' => 'Techo 10*10', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '115', 'nombre' => 'Techo 12*10 tomcat', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '116', 'nombre' => 'Techo 19*14 tomcat hd', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '117', 'nombre' => 'Aires acondicionados de 5 toneladas', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '118', 'nombre' => 'Aviones', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '119', 'nombre' => 'Bases gran Suport Tomcat', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '120', 'nombre' => 'Bases suport plate', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '121', 'nombre' => 'Bases tomcat 12x12', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '122', 'nombre' => 'Bases Pleted Glob. Truss', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '123', 'nombre' => 'Brekera', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '124', 'nombre' => 'Estructura Lhayer 16*4,80*10mts', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '125', 'nombre' => 'Acometida elec 4/0 * mts', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '126', 'nombre' => 'Acometida elect cable 4*6', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '127', 'nombre' => 'Cable thw 2/0', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '128', 'nombre' => 'Cable para acometida electrica * mts.', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '129', 'nombre' => 'Yellow Jackets', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '130', 'nombre' => 'Corner 6 vias Glob. Truss', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '131', 'nombre' => 'Motores CM Lodster 1 ton.', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '132', 'nombre' => 'Metros de acometida 4/0 para transfer', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '133', 'nombre' => 'Controlador motores', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '134', 'nombre' => 'Lona 10x10', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '135', 'nombre' => 'Lona 12x12', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '136', 'nombre' => 'Lona 16x14', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '137', 'nombre' => 'Lona 6x6 transparente', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '138', 'nombre' => 'Lona 8x8', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '139', 'nombre' => 'Vigas aviones', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '140', 'nombre' => 'Grand suport 1 ton Tomcat', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '141', 'nombre' => 'Global truss 0,50 mts', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '142', 'nombre' => 'Global truss 1,00 mts', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '143', 'nombre' => 'Global truss 1,50 mts', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '144', 'nombre' => 'Global truss 3,00 mts', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '145', 'nombre' => 'Global truss circulo 3 mts', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '146', 'nombre' => 'Global truss circulo 5 mts', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '147', 'nombre' => 'Patas negras 7*1,5 mts', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '148', 'nombre' => 'Terminal L', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '149', 'nombre' => 'Honorarios profesionales', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '150', 'nombre' => 'Tecnicos', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '151', 'nombre' => 'Horas extras', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '152', 'nombre' => 'Mano de obra', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '153', 'nombre' => 'Variable corner visagra', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '154', 'nombre' => 'variable corner visagra 26x30', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '155', 'nombre' => 'Variable corner visagra 12x12', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '156', 'nombre' => 'Corner 4 vias Tomcat', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '157', 'nombre' => 'Corner Sleeve Block 26x30', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '158', 'nombre' => 'Gran soporte 12x12 - 1T', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '159', 'nombre' => 'Gran soporte 16x16 - 2T', 'tipo_articulo_id' => '3', 'ind_excento' => '0'),
            array('id' => '160', 'nombre' => 'Articulo de prueba', 'tipo_articulo_id' => '1', 'ind_excento' => '0'),
            array('id' => '163', 'nombre' => 'Diesel', 'tipo_articulo_id' => '4', 'ind_excento' => '1')
        );
        foreach ($arts as $value) {
            App\Articulo::create($value);
        }
    }

}
